language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jglatter/frontend -f Dockerfile.dev .

script: 
    - docker run -e CI=true jglatter/frontend yarn test --coverage